-- 普通用户（USER）默认授予除管理员专用外的可读菜单：仓库读、平台壳读，不含系统管理与写权限。
INSERT INTO sys_role_menu (role_id, menu_id)
SELECT 2, menu_id
FROM (
    SELECT 10 AS menu_id UNION ALL
    SELECT 20 UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL
    SELECT 100 UNION ALL SELECT 110 UNION ALL
    SELECT 111 UNION ALL SELECT 112 UNION ALL SELECT 113 UNION ALL SELECT 117 UNION ALL
    SELECT 114 UNION ALL SELECT 115 UNION ALL SELECT 116 UNION ALL
    SELECT 120 UNION ALL SELECT 121 UNION ALL SELECT 122 UNION ALL SELECT 123 UNION ALL
    SELECT 150 UNION ALL
    SELECT 160 UNION ALL SELECT 161 UNION ALL SELECT 162 UNION ALL SELECT 163 UNION ALL
    SELECT 170 UNION ALL
    SELECT 180 UNION ALL SELECT 181 UNION ALL SELECT 182 UNION ALL SELECT 183
) AS candidate
WHERE NOT EXISTS (
    SELECT 1 FROM sys_role_menu rm WHERE rm.role_id = 2 AND rm.menu_id = candidate.menu_id
);
