# Worktree 数据库隔离注册表（SSOT）
# 供 sync-worktree-env.ps1、start-dev.ps1、reset-db.ps1 使用

$script:WorktreeDbProfiles = @(
    @{
        Branch              = 'main'
        Slug                = 'main'
        WorktreePath        = 'E:/Storage'
        ComposeProjectName  = 'storage-main'
        MysqlPort           = 3307
        MinioPort           = 9000
        MinioConsolePort    = 9001
        MysqlContainer      = 'storage-main-mysql'
        MinioContainer      = 'storage-main-minio'
        MysqlVolume         = 'storage-main_mysql_data'
        MinioVolume         = 'storage-main_minio_data'
    }
    @{
        Branch              = 'feat/material-ledger'
        Slug                = 'material-ledger'
        WorktreePath        = 'E:/Storage-worktrees/material-ledger'
        ComposeProjectName  = 'storage-material-ledger'
        MysqlPort           = 3308
        MinioPort           = 9010
        MinioConsolePort    = 9011
        MysqlContainer      = 'storage-material-ledger-mysql'
        MinioContainer      = 'storage-material-ledger-minio'
        MysqlVolume         = 'storage-material-ledger_mysql_data'
        MinioVolume         = 'storage-material-ledger_minio_data'
    }
    @{
        Branch              = 'feat/material-io'
        Slug                = 'material-io'
        WorktreePath        = 'E:/Storage-worktrees/material-io'
        ComposeProjectName  = 'storage-material-io'
        MysqlPort           = 3309
        MinioPort           = 9020
        MinioConsolePort    = 9021
        MysqlContainer      = 'storage-material-io-mysql'
        MinioContainer      = 'storage-material-io-minio'
        MysqlVolume         = 'storage-material-io_mysql_data'
        MinioVolume         = 'storage-material-io_minio_data'
    }
    @{
        Branch              = 'feat/safety-stock'
        Slug                = 'safety-stock'
        WorktreePath        = 'E:/Storage-worktrees/safety-stock'
        ComposeProjectName  = 'storage-safety-stock'
        MysqlPort           = 3310
        MinioPort           = 9030
        MinioConsolePort    = 9031
        MysqlContainer      = 'storage-safety-stock-mysql'
        MinioContainer      = 'storage-safety-stock-minio'
        MysqlVolume         = 'storage-safety-stock_mysql_data'
        MinioVolume         = 'storage-safety-stock_minio_data'
    }
    @{
        Branch              = 'feat/config-mgmt'
        Slug                = 'config-mgmt'
        WorktreePath        = 'E:/Storage-worktrees/config-mgmt'
        ComposeProjectName  = 'storage-config-mgmt'
        MysqlPort           = 3311
        MinioPort           = 9040
        MinioConsolePort    = 9041
        MysqlContainer      = 'storage-config-mgmt-mysql'
        MinioContainer      = 'storage-config-mgmt-minio'
        MysqlVolume         = 'storage-config-mgmt_mysql_data'
        MinioVolume         = 'storage-config-mgmt_minio_data'
    }
)

function Get-WorktreeDbProfile {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Branch
    )

    $profile = $script:WorktreeDbProfiles | Where-Object { $_.Branch -eq $Branch } | Select-Object -First 1
    if (-not $profile) {
        $known = ($script:WorktreeDbProfiles | ForEach-Object { $_.Branch }) -join ', '
        throw "Unknown branch '$Branch'. Known branches: $known"
    }
    return $profile
}

function Get-CurrentBranchName {
    param(
        [string]$RepoRoot = (Get-Location).Path
    )

    $branch = git -C $RepoRoot branch --show-current 2>$null
    if (-not $branch) {
        throw "Not a git repository or detached HEAD: $RepoRoot"
    }
    return $branch.Trim()
}

function Get-CurrentBranchProfile {
    param(
        [string]$RepoRoot = (Get-Location).Path
    )

    $branch = Get-CurrentBranchName -RepoRoot $RepoRoot
    $profile = Get-WorktreeDbProfile -Branch $branch

    $normalizedRoot = (Resolve-Path -LiteralPath $RepoRoot).Path -replace '\\', '/'
    $normalizedExpected = $profile.WorktreePath -replace '\\', '/'
    if ($normalizedRoot -ne $normalizedExpected) {
        Write-Warning "Current path ($normalizedRoot) does not match registered worktree for branch '$branch' ($normalizedExpected). Using branch profile anyway."
    }

    return $profile
}

function Format-WorktreeEnvContent {
    param(
        [Parameter(Mandatory = $true)]
        [hashtable]$Profile
    )

    $minioEndpoint = "http://localhost:$($Profile.MinioPort)"
    return @"
# Auto-generated by scripts/sync-worktree-env.ps1 - do not commit (.gitignore)
# Branch: $($Profile.Branch) | Compose: $($Profile.ComposeProjectName)

MYSQL_HOST=localhost
MYSQL_PORT=$($Profile.MysqlPort)
MYSQL_DB=storage
MYSQL_USER=storage
MYSQL_PASSWORD=storage123

MINIO_ENDPOINT=$minioEndpoint
MINIO_ACCESS_KEY=minioadmin
MINIO_SECRET_KEY=minioadmin123
MINIO_BUCKET=storage

COMPOSE_PROJECT_NAME=$($Profile.ComposeProjectName)
STORAGE_MYSQL_PORT=$($Profile.MysqlPort)
STORAGE_MINIO_PORT=$($Profile.MinioPort)
STORAGE_MINIO_CONSOLE_PORT=$($Profile.MinioConsolePort)
STORAGE_MYSQL_CONTAINER=$($Profile.MysqlContainer)
STORAGE_MINIO_CONTAINER=$($Profile.MinioContainer)
STORAGE_MYSQL_VOLUME=$($Profile.MysqlVolume)
STORAGE_MINIO_VOLUME=$($Profile.MinioVolume)
"@
}

function Write-WorktreeEnvFile {
    param(
        [Parameter(Mandatory = $true)]
        [hashtable]$Profile,
        [string]$RepoRoot = (Get-Location).Path
    )

    $envPath = Join-Path $RepoRoot '.env'
    $content = Format-WorktreeEnvContent -Profile $Profile
    [System.IO.File]::WriteAllText($envPath, $content, [System.Text.UTF8Encoding]::new($false))
    return $envPath
}

function Import-WorktreeEnvFile {
    param(
        [string]$RepoRoot = (Get-Location).Path
    )

    $envPath = Join-Path $RepoRoot '.env'
    if (-not (Test-Path -LiteralPath $envPath)) {
        throw ".env not found at $envPath. Run scripts/sync-worktree-env.ps1 first."
    }

    Get-Content -LiteralPath $envPath | ForEach-Object {
        $line = $_.Trim()
        if ($line -and -not $line.StartsWith('#')) {
            $eq = $line.IndexOf('=')
            if ($eq -gt 0) {
                $name = $line.Substring(0, $eq).Trim()
                $value = $line.Substring($eq + 1).Trim()
                Set-Item -Path "Env:$name" -Value $value
            }
        }
    }
}

function Get-DockerComposeArgs {
  param([string]$RepoRoot = (Get-Location).Path)

  $envPath = Join-Path $RepoRoot '.env'
  if (Test-Path -LiteralPath $envPath) {
    return @('--env-file', $envPath)
  }
  return @()
}
